version: '3.7'

services:
  iris:
    image:  intersystems/irishealth:2022.1.0DEVIH.39.0
    ports: ["51773:51773", "1972:1972", "57772:57772", "52773:52773", "443:443"]
    container_name: sqlbuilder
    volumes: ["./data:/data", "/src/ObjectScript:/code"]
    environment: [ISC_DATA_DIRECTORY=/data/ifconfig]
    entrypoint: ["/iris-main"]
    command: --key /data/iris.key

